services:
  postgres:
    image: postgres:17
    container_name: postgres-db-intercurso
    restart: always
    environment:
      POSTGRES_DB: intercurso_db
      POSTGRES_USER: intercurso
      POSTGRES_PASSWORD: intercurso
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
