name: Pull Request - Tests & Coverage
on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: pr-${{ github.head_ref  }}--verify
  cancel-in-progress: true

jobs:
  verify:
    name: tests-and-coverage
    if: ${{ !github.event.pull_request.draft }}

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Create virtualenv
        run: uv venv

      - name: Install project
        run: uv pip install .

      - name: Install dev dependencies
        run: uv pip install --group dev

      - name: Run tests
        run: uv run pytest